# Generated by Django 3.1.3 on 2022-02-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_auto_20220214_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='modify_fate',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='modify_fate',
            new_name='modify_date',
        ),
    ]
